import { LegalDocument } from '@/components/LegalDocument'

export default function AcceptableUsePage() {
  return (
    <LegalDocument
      title="Acceptable Use Policy"
      summary="This policy covers how the control plane, replay features, and enforcement artifacts may be used."
      sections={[
        {
          heading: 'Authorized operation only',
          body: [
            'Customers may use the service only for lawful workload authorization, simulation, and supporting governance workflows. Abuse of replay, credential sharing, or unauthorized internal calls is prohibited.',
          ],
        },
        {
          heading: 'No misrepresentation',
          body: [
            'Users may not misstate simulated outputs as live runtime decisions or conceal degraded/fallback posture when presenting proof generated by the platform.',
          ],
        },
        {
          heading: 'Security',
          body: [
            'Attempts to bypass access controls, manipulate proof chains, overload provider integrations, or exploit downstream enforcement contracts are forbidden.',
          ],
        },
      ]}
    />
  )
}
